name: flutter_unity_cli
description: A command-line application for managing flutter unity at scale.
version: 1.0.3
homepage: https://www.xraph.com

executables:
  fuw: main

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  recase: ^3.0.0
  ansicolor: ^1.0.2
  http: ^0.12.1
  path: ^1.7.0
  yaml: ^2.2.1
  args: ^1.6.0
  dart_console: ^0.6.1
  version: ^1.2.0
  tuple: ^1.0.3
  pubspec_yaml: ^2.0.1
  pub_semver: ^1.4.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
